# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waystohelp', '0003_auto_20151101_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waytohelp',
            name='text',
            field=models.TextField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="https://daringfireball.net/projects/markdown/syntax">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. '),
        ),
    ]
