# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0062_soundrecording'),
        ('birds', '0011_auto_20160130_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='main_sound_recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_with_main_recording', to='creations.SoundRecording'),
        ),
    ]
