# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0013_auto_20160204_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='ebird_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
