# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0014_species_ebird_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='ebird_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
