# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0015_auto_20160210_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='species',
            name='family_common',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='species',
            name='order',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='species',
            name='taxon_order',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
