# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0016_auto_20160210_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name=b'Visible on website'),
        ),
    ]
