# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0018_auto_20160210_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='french_name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='nacc_annotation',
        ),
        migrations.RemoveField(
            model_name='species',
            name='nacc_is_accidental',
        ),
        migrations.RemoveField(
            model_name='species',
            name='nacc_is_extinct',
        ),
        migrations.RemoveField(
            model_name='species',
            name='nacc_is_hawaiian',
        ),
        migrations.RemoveField(
            model_name='species',
            name='nacc_is_introduced',
        ),
        migrations.RemoveField(
            model_name='species',
            name='nacc_is_misplaced',
        ),
        migrations.RemoveField(
            model_name='species',
            name='nacc_is_nonbreeding',
        ),
    ]
