# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0021_add_autoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birds.TaxonomicGroup'),
        ),
    ]
