# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0023_auto_20160211_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='en_IOC',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
