# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0027_auto_20160211_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='report_as',
        ),
    ]
