# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0029_auto_20160212_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomicgroup',
            name='level',
        ),
        migrations.RemoveField(
            model_name='taxonomicgroup',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='species',
            name='absolute_position',
        ),
        migrations.RemoveField(
            model_name='species',
            name='parent',
        ),
        migrations.DeleteModel(
            name='TaxonomicGroup',
        ),
        migrations.DeleteModel(
            name='TaxonomicLevel',
        ),
    ]
