# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0030_auto_20160212_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='ebird_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxon_order',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, unique=True),
            preserve_default=False,
        ),
    ]
