# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0034_auto_20160212_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='has_wikipedia_url',
            field=models.BooleanField(default=False),
        ),
    ]
