# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0036_auto_20160218_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='main_sound_recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_with_main_recording', to='creations.SoundRecording'),
        ),
    ]
