# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-17 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0037_auto_20160223_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='has_mn_bird_atlas_url',
            field=models.BooleanField(default=False),
        ),
    ]
