# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0059_auto_20160109_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='display_title',
            field=models.BooleanField(default=True),
        ),
    ]
