# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0060_webpage_display_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalproject',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='webpage',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AddField(
            model_name='externalproject',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webpage',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="https://daringfireball.net/projects/markdown/syntax">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. '),
        ),
        migrations.AlterField(
            model_name='creation',
            name='description',
            field=models.TextField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="https://daringfireball.net/projects/markdown/syntax">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. '),
        ),
        migrations.AlterField(
            model_name='radioprogram',
            name='transcript',
            field=models.TextField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="https://daringfireball.net/projects/markdown/syntax">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. '),
        ),
        migrations.AlterField(
            model_name='research',
            name='attribution',
            field=models.CharField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="https://daringfireball.net/projects/markdown/syntax">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. ', max_length=200),
        ),
        migrations.AlterField(
            model_name='research',
            name='text',
            field=models.TextField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="https://daringfireball.net/projects/markdown/syntax">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. '),
        ),
        migrations.AlterField(
            model_name='researchcategory',
            name='notes',
            field=models.TextField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="https://daringfireball.net/projects/markdown/syntax">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. '),
        ),
        migrations.AlterField(
            model_name='speakingprogramfile',
            name='description',
            field=models.TextField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="https://daringfireball.net/projects/markdown/syntax">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. '),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=models.TextField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="https://daringfireball.net/projects/markdown/syntax">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. '),
        ),
    ]
