# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0061_auto_20160130_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundRecording',
            fields=[
                ('creation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='creations.Creation')),
                ('file', models.FileField(upload_to=b'soundrecordings')),
                ('date_recorded', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
            bases=('creations.creation',),
        ),
    ]
