# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0062_soundrecording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abafieldguideimage',
            name='creation_ptr',
        ),
        migrations.DeleteModel(
            name='ABAFieldGuideImage',
        ),
    ]
