# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0063_auto_20160204_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
