# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0064_webpage_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioProgramMissedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
