# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 04:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0065_radioprogrammisseddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioprogrammisseddate',
            name='air_date',
            field=models.DateField(default=datetime.datetime(2016, 2, 9, 4, 15, 37, 121219, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
