# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0066_radioprogrammisseddate_air_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radioprogrammisseddate',
            options={'ordering': ['-air_date']},
        ),
    ]
