# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0068_soundrecording_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioprogram',
            name='date_is_estimate',
            field=models.BooleanField(default=False),
        ),
    ]
