# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0069_radioprogram_date_is_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioprogram',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b'radio'),
        ),
    ]
