# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0070_auto_20160322_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioprogram',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=b'radio'),
            preserve_default=False,
        ),
    ]
