# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0071_auto_20160322_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radioprogram',
            old_name='supplemental_content_url',
            new_name='blog_url',
        ),
    ]
