# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0072_auto_20160405_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
